# Generated by Django 3.0.4 on 2020-03-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.TextField(blank=True),
        ),
    ]
