# Generated by Django 3.0.2 on 2020-03-02 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
